config/routes.rb
Rails.application.routes.draw do

  
  get 'quizlist/index'
  get 'quizlist/favorite'
  delete 'quizlist/:id', to: 'quizlist#destroy'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'home/index'
  get 'home/title_list'
  get 'home/question'
  get 'home/list'
  post 'home/question'
  delete 'home/:id', to: 'home#destroy'
  
  get 'settings/password'
  post 'settings/password'
  
  devise_scope :user do
    root :to => "devise/sessions#new"
  end
  
  resources 'upload', only: :index do
    collection {post :import}
  end
  
  resources 'favorite', only: [:create,:destroy]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!
    before_action :get_sign_in_user
    
    include HomeHelper
    
    
    def index
    end
    
    
    def title_list
        if params[:req] == "learn"
            @nav_title = "学習する"
        else
            @nav_title = "一覧を見る"
        end
        @title = Story.group(:title).count.keys
    end
    
    def question

    ### Initialize process
        if params[:story_id]
            #CAUTION index starts from 0, however it will be described as 1 in view
            @index = 0
            @question = select_question_whose_status_is_(params[:selecting_status],params[:story_id])[@index]
            if @question.present?
                @total = select_question_whose_status_is_(params[:selecting_status],params[:story_id]).count
            else
                @total = "--"
                @index = -1
            end
            @story = Story.find(params[:story_id])
            @status = params[:selecting_status]
        end

    ### Ajax Process
        if params[:position] == "question_page"     
            transition_from_question_to_answer
        end
        
        if params[:position] == "answer_page"     
            transition_from_answer_to_question
        end
        
        if params[:position] == "favorite"
            favorite =  @current_user.favorites.find_by(question_id: params[:question_id])
            if favorite.present?
                favorite.delete
            else
                @current_user.favorites.build(question_id: params[:question_id]).save
            end
            @question = Question.find(params[:question_id])
            @aim = 3
        end
            
        respond_to do |format|
            format.html
            format.js
        end
    end
    
    def destroy
        story = Story.find(params[:id])
        story.questions.each do |question|
            if question.favorites
                question.favorites.delete_all
            end
            if question.statuses
                question.statuses.delete_all
            end
        end
        story.questions.delete_all
        story.destroy
        redirect_back(fallback_location: root_path)
    end
    
   
   
    private
    
   
    def transition_from_question_to_answer
        @selecting_status = params[:selecting_sta]
        @question = Question.find(params[:this_question_id])
        @index = params[:ind]
        @total = params[:total]
        @aim = 1
    end
    
    def transition_from_answer_to_question
        story = Question.find(params[:this_question_id]).story
        @selecting_status = params[:selecting_sta]
        @index = params[:ind].to_i + 1
        @question = select_question_whose_status_is_(params[:selecting_sta], story.id)[@index]
        @total = params[:total]
        request_status = current_user.statuses.where(question_id: params[:this_question_id]).first_or_create
        request_status.update(status: params[:request_status])
        
        if @index == @total.to_i
            @aim = 2
            #Javascriptでは条件分岐の条件外スコープであってもnillであることは許されない。
            #そのため偽オブジェクト(使わないオブジェクト)@questionを生成
            @question = Question.first
        elsif @question.present?
             @aim = 0
        else
            @aim = 2
        end
    end

end

app/helpers/home_helper.rb
module HomeHelper
    
    
    def select_question_whose_status_is_(request_status,story)
        whole_questions = []
        if request_status == "all"
            whole_questions = Question.all.where(story_id: story)
        elsif request_status == "favorite"
            whole_questions = @current_user.favorite_questions.where(story_id: story)
        elsif request_status == 'unclear'
            already_answered_question_ids = @current_user.questions.where(story_id: story).ids
            all_question = Question.all.where(story_id: story)
            if already_answered_question_ids.present?
                whole_questions = all_question.where.not('id IN (?)',already_answered_question_ids)
            else
                whole_questions = all_question
            end
        else
            question_ids_which_has_selected_status = @current_user.statuses.where(status: request_status).ids
            whole_questions = Story.find(story).questions.where('id IN (?)',question_ids_which_has_selected_status)
        end
        return whole_questions
    end
    
    def status(question)
        tmp = question.statuses.find_by(user_id: @current_user.id)
        if tmp.present?
            status = tmp.status
        else
            status = "hoge"
        end
        return status
    end
            
    
    
end

app/views/home/index.html.erb
<% content_for :cover do %>
    <%= render 'layouts/navbar', title: "単語帳アプリ" %>
<% end %>
<div class="col-md-5" style="test-align:center;" >
    <%= render 'layouts/flash_messages' %>
    <%= link_to "学習する",home_title_list_path(req: "learn"), class: "btn btn-default col-xs-12", style: "margin-top:40px;" %>
    <%= link_to "一覧を見る", home_title_list_path(req: "show"), class: "btn btn-default col-xs-12", style: "margin-top:20px;" %>
</div>

app/views/home/list.html.erb
<% content_for :cover do %>
    <header>
        <nav class="navbar navbar-default navbar-static-top", style="background-color:skyblue; height:70px; margin-bottom:0px;">
        	<div class="container">
        		<div class="navbar-header">
        			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample">
        				<span class="sr-only">Toggle navigation</span>
        				<span class="icon-bar"></span>
        				<span class="icon-bar"></span>
        				<span class="icon-bar"></span>
        			</button>
        			<h1 class="selecting_status" style="color:white; margin:0px 10px; padding:10px; font-size:20px;">
        			    <%= @story.title %>
        			    <br>
        			    <% if @status == "unclear"%>
        			         第<%= @story.number %>話: 未回答のみ
        			    <% elsif @status == "correct" %>
        			         第<%= @story.number %>話: <i class="far fa-circle"></i>のみ
        			    <% elsif @status == "incorrect"%>
        			         第<%= @story.number %>話: <i class="fas fa-times"></i>のみ
        			    <% elsif @status == "favorite" %>
        			         第<%= @story.number %>話: <i class="fas fa-star"></i>のみ
        			    <% elsif @status == "all" %>
        			         第<%= @story.number %>話: 全て
        			     <% end %>
        			</h1>
        		</div>
        		<div class="collapse navbar-collapse" id="navbarEexample" style="text-align:right; background-color:skyblue;">
        			<ul class="nav navbar-nav navbar-right">
        				<li><%= link_to 'ログアウト',destroy_user_session_path, method: :delete %></li>
        				<li><%= link_to 'ホームに戻る', home_index_path %></li>
        			</ul>
        		</div>
        	</div>
        </nav>
        <nav class="sub_nav">
           <p class="inline" style="margin-left:20px;">未 <%= select_question_whose_status_is_("unclear",@story.id).count %></p>
           <p class="inline"><i class="far fa-circle" style="color:red;"></i> <%= select_question_whose_status_is_("correct",@story.id).count %></p>
           <p class="inline"><i class="fas fa-times" style="color:blue;"></i> <%= select_question_whose_status_is_("incorrect",@story.id).count %></p>
        </nav>
    </header>
<% end %>

<table>
    <tr>
        <th class="col-xs-10"></th>
        <th class="col-xs-1"></th>
        <th class="col-xs-1"></th>
        <th class="col-xs-1"></th>
    </tr>
    <tbody  class="jscroll"> 
        <%= render 'layouts/question_show',questions: @questions %>
    </tbody>

</table>
<%= paginate @questions %>

app/views/home/list.js.erb
$('#<%= @question.id %>').html("<%= escape_javascript(render 'layouts/favorite_starmini', question: @question) %>");

app/views/home/question.html.erb
<% content_for :cover do %>
    <header>
        <nav class="navbar navbar-default navbar-static-top", style="background-color:skyblue; height:70px; margin-bottom:0px;">
        	<div class="container">
        		<div class="navbar-header">
        			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample">
        				<span class="sr-only">Toggle navigation</span>
        				<span class="icon-bar"></span>
        				<span class="icon-bar"></span>
        				<span class="icon-bar"></span>
        			</button>
        			<h1 class="selecting_status" style="color:white; margin:0px 10px; padding:10px; font-size:20px;">
        			    <%= @story.title %>
        			    <br>
        			    <% if @status == "unclear"%>
        			         第<%= @story.number %>話: 未回答のみ
        			    <% elsif @status == "correct" %>
        			         第<%= @story.number %>話: <i class="far fa-circle"></i>のみ
        			    <% elsif @status == "incorrect"%>
        			         第<%= @story.number %>話: <i class="fas fa-times"></i>のみ
        			    <% elsif @status == "favorite" %>
        			         第<%= @story.number %>話: <i class="fas fa-star"></i>のみ
        			    <% elsif @status == "all" %>
        			         第<%= @story.number %>話: 全て
        			     <% end %>
        			</h1>
        		</div>
        		<div class="collapse navbar-collapse" id="navbarEexample" style="text-align:right; background-color:skyblue;">
        			<ul class="nav navbar-nav navbar-right">
        				<li><%= link_to 'ログアウト',destroy_user_session_path, method: :delete %></li>
        				<li><%= link_to 'ホームに戻る', home_index_path %></li>
        			</ul>
        		</div>
        	</div>
        </nav>
        <nav class="sub_nav">
            <p class="fraction" id='numerator' style="margin-left:20px;"><%= @index+1 %></p>
            <p class="fraction">/ <%= @total %></p>
        </nav>
    </header>
<% end %>


<div class="wraper">
   
    <% if @question.present? %>
    
        <h1 id="question", style="text-align:center;"><%= @question.question %></h1>
        <hr>
        <h1 id="answer", style="text-align:center; margin-top:30px;"><!-- answer --></h1>
        

        <div id="audio">
            <%= render 'layouts/audio', sound_file: @question.sound_file, num: @question.id %>
        </div>
        <div id="favorite">
            <%= render 'layouts/favorite_star', question: @question %>
        </div>
        
        <%= content_for :cover2 do %>
            <footer id="footer">
                <%= render 'layouts/question_footer', this_question_id: @question.id, selecting_sta: @status, ind: @index, total: @total %>
                <%#= render 'layouts/answer_footer', this_question_id: @question.id, category: @selecting_status %>
            </footer>
        <% end %>
    <% else %>
        <h1 style="text-align:center;">問題が見つかりません!</h1>
    <% end %>
    
    <script>
        window.addEventListener('beforeunload', function(e) {
            e.returnValue = 'このページを離れると解答は記録されません';
        }, false);
    </script>
    
</div>

app/views/home/question.js.erb
<%# if transition from question to answer %>
if(<%= @aim %> == 0){
    $('#footer').html("<%= escape_javascript(render 'layouts/question_footer', this_question_id: @question.id, selecting_sta: @selecting_status, ind: @index, total: @total) %>");
    $('#answer').html("");
    $('#question').html("<%= @question.question %>");
    $('#audio').html("<%= escape_javascript(render 'layouts/audio', sound_file: @question.sound_file , num: @question.id) %>");
    $('#favorite').html("<%= escape_javascript(render 'layouts/favorite_star', question: @question) %>");
    $('#numerator').html("<%= @index.to_i+1 %>")
}

if(<%= @aim %> == 1){
    $('#footer').html("<%= escape_javascript(render 'layouts/answer_footer', question_id: @question.id, selecting_sta: @selecting_status, ind: @index, total: @total) %>");
    $('#answer').html("<%= @question.answer %>");
    $('#favorite').html("<%= escape_javascript(render 'layouts/favorite_star', question: @question) %>");
}

if(<%= @aim %> == 2 ){
    $('#footer').html("");
    $('#answer').html("");
    $('#question').html("問題は以上です!");
    $('#audio').html("")
    $('#favorite').html("");
}

if(<%= @aim %> == 3 ){
   $('#favorite').html("<%= escape_javascript(render 'layouts/favorite_star', question: @question) %>");
}

app/views/home/title_list.html.erb
<% content_for :cover do %>
   <%= render 'layouts/navbar', title: @nav_title %>
<% end %>
<% if @current_user.email == "test@gmail.com"%>
    <h4>管理者用画面</h4>
    <p>この画面ではストーリー単位での削除を行えます(この処理には時間がかかります。)クイズ単位の削除は、一覧ページから行ってください</p>
<% end %>

<div class="panel-group" id="accordion">
    <% @title.each do |title| %>
        <% story = Story.find_by(title: title) %>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4  class="panel-title" data-toggle="collapse"  data-target="#collapse<%= story.id %>">
                    <%= story.title %>
                </h4>
            </div>
            <div id="collapse<%= story.id %>" class="panel-collapse collapse">
              <% Story.where(title: story.title).order("number").each do |no_story| %>
                <ul class="list-group">
                  <% @id = no_story.id %>
                    <li class="list-group-item"><a data-toggle="modal" href="#modal-sample<%= no_story.id %>">第<%= no_story.number %>話</a></li>
                      <% if params[:req] == "learn" %>
                          <%= render 'layouts/modal_learn', id: @id %>
                      <% elsif params[:req] == "show" %>
                          <%= render 'layouts/modal_show', id: @id %>
                      <% end %>
                     <% if @current_user.email == "test@gmail.com"%>
                        <li class="list-group-item" style="height:30px; color:red;"><%= button_to "この話を削除する", { :action => "destroy", :id => @id }, :confirm => "本当に削除しますか?", :method => :delete %></li>
                    <% end %>
                </ul>
              <% end %>
            </div>
        </div>
    <% end %>
</div>