config/routes.rb
Rails.application.routes.draw do

  
  get 'quizlist/index'
  get 'quizlist/favorite'
  delete 'quizlist/:id', to: 'quizlist#destroy'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'home/index'
  get 'home/title_list'
  get 'home/question'
  get 'home/list'
  post 'home/question'
  delete 'home/:id', to: 'home#destroy'
  
  get 'settings/password'
  post 'settings/password'
  
  devise_scope :user do
    root :to => "devise/sessions#new"
  end
  
  resources 'upload', only: :index do
    collection {post :import}
  end
  
  resources 'favorite', only: [:create,:destroy]
end

app/views/layouts/_answer_footer.html.erb
<div class="answer_select">
    <%= link_to(home_question_path(this_question_id: question_id, request_status: "correct", selecting_sta: selecting_sta, position: "answer_page", ind: ind, total: total), remote: true) do %>
               <button class="btn btn-danger col-xs-6"><i class="far fa-circle fa-5x"></i></button>
    <% end %>
    <%= link_to(home_question_path(this_question_id: question_id, request_status: "incorrect", selecting_sta: selecting_sta, position: "answer_page", ind: ind, total: total), remote: true) do %>
               <button class="btn btn-primary col-xs-6"><i class="fas fa-times fa-5x"></i></button>
    <% end %>
</div>

app/views/layouts/_audio.html.erb
<button><i class="fas fa-play fa-border fa-4x" type="button" id="audiobutton<%=num%>" value=""  ></i></button> 
<script>
    $(function() {
        if(!audio){
            var audio = new Audio("");
        }
        var src = "";
        var name = "再生できません";
        var state = 0;  // 0:pause, 1:playing
        if(audio.canPlayType){
            if(audio.canPlayType("audio/ogg") != ""){
                src = "<%=  ENV['S3_HOST'] + "0000.mp3" %>";
            }
        }
        if(src != ""){
            $("#audiobutton<%=num%>").click(function(ev){
                //ajaxはページが読み込まれるわけではないので、処理はこの .clickで行うことになる
                audio.src = "<%= ENV['S3_HOST'] + sound_file %>";
                if(state == 0){
                    audio.load();
                    audio.play();
                    state = 0;
                }else{
                    audio.pause();
                    state = 0;
                }
            });
            $("#footer").click(function(ev){
                audio.pause();
                state = 0;
            });
            $("#navbarEexample").click(function(ev){
                audio.pause();
                state = 0;
            });
        }
    });
</script>

app/views/layouts/_audiomini.html.erb
<button><i class="fas fa-play fa-1x" type="button" id="audiobutton<%=num%>" value=""  ></i></button> 
<script>
    $(function() {
        if(!audio){
            var audio = new Audio("");
        }
        var src = "";
        var name = "再生できません";
        var state = 0;  // 0:pause, 1:playing
        if(audio.canPlayType){
            if(audio.canPlayType("audio/ogg") != ""){
                src =  "<%=  ENV['S3_HOST'] + "0000.mp3" %>";
            }
        }
        if(src != ""){
            $("#audiobutton<%=num%>").click(function(ev){
                //ajaxはページが読み込まれるわけではないので、処理はこの .clickで行うことになる
                audio.src = "<%= ENV['S3_HOST'] + sound_file %>";
                if(state == 0){
                    audio.load();
                    audio.play();
                    state = 0;
                }else{
                    audio.pause();
                    state = 0;
                }
            });
            $("#footer").click(function(ev){
                audio.pause();
                state = 0;
            });
            $("#navbarEexample").click(function(ev){
                audio.pause();
                state = 0;
            });
        }
    });
</script>

app/views/layouts/_error_messages.html.erb
<% if false %>
<% if model.errors.any? %>
    <div class="alert alert-warning">
        <ul>
            <% model.errors.full_messages.each do |message| %>
                 <li><%= message %></li>   
            <% end %>
        </ul>
    </div>
<% end %>
<% end %>

app/views/layouts/_favorite_star.html.erb
<% if question.favorites.where(user_id: @current_user.id).present? %>
    <%= link_to(home_question_path(question_id: @question.id, position: "favorite"), remote: true) do %>
        <i class="fas fa-star fa-5x" style="color:yellow;"></i>
    <% end %>
<% else %>
    <%= link_to(home_question_path(question_id: question.id, position: "favorite"), remote: true) do %>
        <i class="fas fa-star fa-5x" style="color:gray;"></i>
    <% end %>
<% end %>

app/views/layouts/_favorite_starmini.html.erb
<% if question.favorites.where(user_id: @current_user.id).present? %>
    <%= link_to(quizlist_index_path(question_id: question.id, position: "favorite"), remote: true) do %>
        <i class="fas fa-star fa-1x" style="color:yellow;"></i>
    <% end %>
<% else %>
    <%= link_to(quizlist_index_path(question_id: question.id, position: "favorite"), remote: true) do %>
        <i class="fas fa-star fa-1x" style="color:gray;"></i>
    <% end %>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-success" style="margin-top:10px;"><%= message %></div>
<% end %>

app/views/layouts/_modal.html.erb
<div class="modal fade" id="modal-sample<%= id %>" tabindex="-1">
  <div class="modal-dialog modal-lg">
    
    <!-- 3.モーダルのコンテンツ -->
    <div class="modal-content" style="background-color:skyblue;">
      <div class="modal-body">
         <!-- 送るべき情報  Status タイトル 何話メカ -->
         <!-- 問題数0の場合は表示させないことにする -->
        <%= link_to(home_question_path(story_id: id, selecting_status: "unclear")) do %><button class="btn btn-default col-xs-8 col-xs-offset-2">未回答のみ <%= select_question_whose_status_is_("unclear",id).count %> </button><% end %>
        <%= link_to(home_question_path(story_id: id, selecting_status: "correct")) do %><button class="btn btn-default col-xs-8 col-xs-offset-2"><i class="far fa-circle"></i>のみ <%= select_question_whose_status_is_("correct",id).count %></button><% end %>
        <%= link_to(home_question_path(story_id: id, selecting_status: "incorrect")) do %><button class="btn btn-default col-xs-8 col-xs-offset-2"><i class="fas fa-times"></i>のみ <%= select_question_whose_status_is_("incorrect",id).count %></button><% end %>
        <%= link_to(home_question_path(story_id: id, selecting_status: "favorite")) do %><button class="btn btn-default col-xs-8 col-xs-offset-2"><i class="fas fa-star"></i>のみ <%= select_question_whose_status_is_("favorite",id).count %></button><% end %>
        <%= link_to(home_question_path(story_id: id, selecting_status:   "all")) do %><button class="btn btn-default col-xs-8 col-xs-offset-2">全て <%= select_question_whose_status_is_("all",id).count %></button><% end %>
      </div>
      <!-- 6.モーダルのフッタ -->
      <div class="modal-footer">
          <button type="button" class="close btn btn-default" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_modal_learn.html.erb
<div class="modal fade" id="modal-sample<%= id %>" tabindex="-1">
  <div class="modal-dialog modal-lg">
    
    <!-- 3.モーダルのコンテンツ -->
    <div class="modal-content" style="background-color:skyblue;">
        <h4 style="color:white; text-align:center;">クイズ画面へ</h4>
        <%= link_to(home_question_path(story_id: id, selecting_status: "unclear")) do %><button class="btn btn-default col-xs-8 col-xs-offset-2">未回答のみ <%= select_question_whose_status_is_("unclear",id).count %> </button><% end %>
        <%= link_to(home_question_path(story_id: id, selecting_status: "correct")) do %><button class="btn btn-default col-xs-8 col-xs-offset-2"><i class="far fa-circle"></i>のみ <%= select_question_whose_status_is_("correct",id).count %></button><% end %>
        <%= link_to(home_question_path(story_id: id, selecting_status: "incorrect")) do %><button class="btn btn-default col-xs-8 col-xs-offset-2"><i class="fas fa-times"></i>のみ <%= select_question_whose_status_is_("incorrect",id).count %></button><% end %>
        <%= link_to(home_question_path(story_id: id, selecting_status: "favorite")) do %><button class="btn btn-default col-xs-8 col-xs-offset-2"><i class="fas fa-star"></i>のみ <%= select_question_whose_status_is_("favorite",id).count %></button><% end %>
        <%= link_to(home_question_path(story_id: id, selecting_status:   "all")) do %><button class="btn btn-default col-xs-8 col-xs-offset-2">全て <%= select_question_whose_status_is_("all",id).count %></button><% end %>
      <!-- 6.モーダルのフッタ -->
      <div class="modal-footer">
          <button type="button" class="close btn btn-default" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_modal_show.html.erb
<div class="modal fade" id="modal-sample<%= id %>" tabindex="-1">
  <div class="modal-dialog modal-lg">
    
    <!-- 3.モーダルのコンテンツ -->
    <div class="modal-content" style="background-color:skyblue;">
        <h4 style="color:white; text-align:center;">一覧表示へ</h4>
        <%= link_to(quizlist_index_path(story_id: id, selecting_status: "unclear")) do %><button class="btn btn-default col-xs-8 col-xs-offset-2">未回答のみ <%= select_question_whose_status_is_("unclear",id).count %> </button><% end %>
        <%= link_to(quizlist_index_path(story_id: id, selecting_status: "correct")) do %><button class="btn btn-default col-xs-8 col-xs-offset-2"><i class="far fa-circle"></i>のみ <%= select_question_whose_status_is_("correct",id).count %></button><% end %>
        <%= link_to(quizlist_index_path(story_id: id, selecting_status: "incorrect")) do %><button class="btn btn-default col-xs-8 col-xs-offset-2"><i class="fas fa-times"></i>のみ <%= select_question_whose_status_is_("incorrect",id).count %></button><% end %>
        <%= link_to(quizlist_index_path(story_id: id, selecting_status: "favorite")) do %><button class="btn btn-default col-xs-8 col-xs-offset-2"><i class="fas fa-star"></i>のみ <%= select_question_whose_status_is_("favorite",id).count %></button><% end %>
        <%= link_to(quizlist_index_path(story_id: id, selecting_status:   "all")) do %><button class="btn btn-default col-xs-8 col-xs-offset-2">全て <%= select_question_whose_status_is_("all",id).count %></button><% end %>
      <!-- 6.モーダルのフッタ -->
      <div class="modal-footer">
          <button type="button" class="close btn btn-default" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<header>
    <nav class="navbar navbar-default navbar-static-top", style="background-color:skyblue; height:60px;">
    	<div class="container">
    		<div class="navbar-header">
    			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample" aria-expanded="false">
    				<span class="sr-only">Toggle navigation</span>
    				<span class="icon-bar"></span>
    				<span class="icon-bar"></span>
    				<span class="icon-bar"></span>
    			</button>
    			<h1 style="color:white; margin:0px 10px; padding:10px; font-size:30px;"><%= title %></h1>
    		</div>
    		<div class="collapse navbar-collapse" id="navbarEexample" style="text-align:right; background-color:skyblue;">
    			<ul class="nav navbar-nav navbar-right">
    				<li><%= link_to 'ログアウト',destroy_user_session_path, method: :delete, data: { confirm: "You sure?" } %></li>
    				<li><%= link_to 'ホームに戻る', home_index_path %></li>
    			</ul>
    		</div>
    	</div>
    </nav>
</header>

app/views/layouts/_question_footer.html.erb
<div class="question_footer">
    <%= link_to(home_question_path(this_question_id: this_question_id, selecting_sta: selecting_sta, ind: ind, position: "question_page", total: total), remote: true) do %>
             <h1>解答を表示</h1>
    <% end %>
</div>

app/views/layouts/_question_show.html.erb
<% questions.each do |question| %>
    <tr style="border-bottom:groove;">
        <td>
            <p style="margin-bottom: 0px;"><%= question.question %></p>
            <p style="margin-top: 0px;"><%= question.answer %></p>
        </td>
        <td>
            <%= render 'layouts/audiomini', sound_file: question.sound_file, num: question.id %>
        </td>
        <td class="star" id=<%= question.id %>>
            <%= render 'layouts/favorite_starmini', question: question %>
        </td>
        <td>
            <% if status(question) == "correct" %>
                <i class="far fa-circle" style="color:red;"></i>
            <% elsif status(question) == "incorrect" %>
                <i class="fas fa-times" style="color:blue;"></i>
            <% else %>
                <p>未</p>
            <% end %>
        </td>
    </tr>
<% end %>

app/views/layouts/_question_show_for_owner.html.erb
<tr>
    <th class="col-xs-9"></th>
    <th class="col-xs-1"></th>
    <th class="col-xs-1"></th>
    <th class="col-xs-1"></th>
    <th class="col-xs-1"></th>
</tr>
<tbody class="jscroll">
    <% questions.each do |question| %>
        <tr style="border-bottom:groove;">
            <td>
                <p style="margin-bottom: 0px;"><%= question.question %></p>
                <p style="margin-top: 0px;"><%= question.answer %></p>
            </td>
            <td>
                <%= render 'layouts/audiomini', sound_file: question.sound_file, num: question.id %>
            </td>
            <td class="star" id=<%= question.id %>>
                <%= render 'layouts/favorite_starmini', question: question %>
            </td>
            <td>
                <% if status(question) == "correct" %>
                    <i class="far fa-circle" style="color:red;"></i>
                <% elsif status(question) == "incorrect" %>
                    <i class="fas fa-times" style="color:blue;"></i>
                <% else %>
                    <p>未</p>
                <% end %>
            </td>
            <td>
               　<%= button_to "削除", { :action => "destroy", :id => question.id }, :confirm => "本当に削除しますか?", :method => :delete %>
            </td>
        </tr>
    <% end %>
</tbody>